# Generated by Django 3.1.6 on 2021-02-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='followers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followsUser', to='network.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='specificUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='specificUser', to='network.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedByUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
