# Generated by Django 3.1.6 on 2021-02-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210221_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followersOfUser', to=settings.AUTH_USER_MODEL)),
                ('specificUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOfFollowers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FollowsOfUser', to=settings.AUTH_USER_MODEL)),
                ('specificUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserWhoFollows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
